language: java
jdk: oraclejdk8
os: linux
dist: bionic
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - ./mvnw flyway:migrate
before_deploy:
  - ./mvnw clean package
deploy:
  provider: heroku
  strategy: api
  app: envibe
  on:
    branch: master
  edge: true
  run: ./mvnw flyway:migrate