language: java
jdk: openjdk8
os: linux
dist: bionic
#services:
#  - postgresql
#env:
#  global:
#    - JDBC_DATABASE_URL=jdbc:postgres://postgres@127.0.0.1:5432/travis_ci_test
#    - PGPORT=5432
before_install:
  - chmod +x mvnw
#before_script:
#  - psql -c 'create database travis_ci_test;' -U postgres
#  - ./mvnw flyway:migrate
before_deploy:
  - ./mvnw clean package
deploy:
  provider: heroku
  strategy: api
  app: envibe
  on:
    branch: master
  edge: true
  run: ./mvnw flyway:migrate