language: java
# Use the OSS implementation of Oracle Java 1.8.0.
jdk: openjdk8
# Use Ubuntu Linux 18.04 Bionic to match Heroku's environment.
os: linux
dist: bionic
# Use PostgreSQL to match Heroku's environment.
# Trying to use version 12.2 causes issues and is not worth pursuing.
services:
  - postgresql
  - redis
# Install Graphviz as it is required by the UML class generator.
addons:
  apt:
    packages:
      - graphviz
      - tree
    update: true
  chrome: stable
# Specify environment variables for database integration.
env:
  global:
    - JDBC_DATABASE_URL=jdbc:postgresql:travis_ci_test?user=postgres
    - PGPORT=5432
    - REDIS_URL=redis://localhost:6379
    - MAVEN_OPTS=-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
before_install:
  # For some reason, we need to re-install Maven Wrapper and set the execute bit on the .sh file.
  - mvn -N io.takari:maven:wrapper -B -Dmaven.test.skip=true -T2 -q
  - chmod +x ./mvnw
# Initialize the database and perform all necessary migrations.
before_script:
  - psql -c 'CREATE DATABASE travis_ci_test;' -U postgres
  - mvn flyway:migrate -e -B -Dmaven.test.skip=true -T1
script:
  - mvn compiler:testCompile -B -Dmaven.test.skip=true -T2 -q
  - mvn test -B -T1 -Dspring-boot.run.arguments=--logging.level.org.springframework=ERROR,--logging.level.com.envibe=ERROR
after_success:
  - echo "Raw slug size of application $(du -sh ./)/500MB (without compression)"
before_deploy:
  # Delete the /target folder.
  #- mvn clean -B -Dmaven.test.skip=true -T2 -q # This removes the /apidocs folder
  # Package as JAR file for deployment onto Heroku.
  - mvn package -B -Dmaven.test.skip=true -T2 -q
  # Generate internal code documentation site for GitHub Pages.
  - mvn javadoc:javadoc -B -Dmaven.test.skip=true -T2 -q
deploy:
  - provider: heroku
    # Use API method to avoid git collision issues.
    strategy: api
    app: envibe
    # Only deploy on master branch builds.
    on:
      branch: master
    # Use deploy API v2 as v1 is deprecated
    edge: true
  - provider: pages
    github_token: $GITHUB_TOKEN
    keep_history: false
    local_dir: ./target/site/apidocs
    target_branch: gh-pages
    on:
      branch: master
