language: java
# Use the OSS implementation of Oracle Java 1.8.0.
jdk: openjdk8
# Use Ubuntu Linux 18.04 Bionic to match Heroku's environment.
os: linux
dist: bionic
# Use PostgreSQL to match Heroku's environment.
# Trying to use version 12.2 causes issues and is not worth pursuing.
services:
  - postgresql
# Specify environment variables for database integration.
env:
  global:
    - JDBC_DATABASE_URL=jdbc:postgresql:travis_ci_test?user=postgres
    - PGPORT=5432
# For some reason, we need to re-install Maven Wrapper and set the execute bit on the .sh file.
before_install:
  - mvn -N io.takari:maven:wrapper
  - chmod +x ./mvnw
# Initialize the database and perform all necessary migrations.
before_script:
  - psql -c 'CREATE DATABASE travis_ci_test;' -U postgres
  - mvn flyway:migrate
# Build project into JAR file for deployment onto Heroku.
before_deploy:
  - mvn clean package
deploy:
  provider: heroku
  # Use API method to avoid git collision issues.
  strategy: api
  app: envibe
  # Only deploy on master branch builds.
  on:
    branch: master
  # Use deploy API v2 as v1 is deprecated
  edge: true
  # Run database migrations on remote server before booting.
  run: mvn flyway:migrate