@startuml

    namespace com.envibe.envibe.config {

        class RedisConfig [[RedisConfig.html]] {
            +jedisConnectionFactory(): JedisConnectionFactory
            +redisTemplate(): RedisTemplate<String, Object>
        }

        class SecurityConfig [[SecurityConfig.html]] {
            +configureGlobal(AuthenticationManagerBuilder): void
            #configure(HttpSecurity): void
            +passwordEncoder(): PasswordEncoder
        }

        abstract class org.springframework.security.config.annotation.web.configuration.WebSecurityConfigurerAdapter
        org.springframework.security.config.annotation.web.configuration.WebSecurityConfigurerAdapter <|-- SecurityConfig

    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
