@startuml

    class CachedItem [[CachedItem.html]] {
        +CachedItem()
        +CachedItem(String, String, String)
        +getPurpose(): String
        +getUserTag(): String
        +getPayload(): String
        +setPayload(String): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
